spring: 
  profiles:
    active:
    - local

---


spring:   profiles:    - local
    
  mvc:
    view:
      prefix: "/WEB-INF/views"
      suffix: ".jsp"
    
  datasource: 
     url: jdbc:mysql://localhost:3306/Project?characterEncoding=UTF-8&serverTimezone=UTC
     username: root 
     password: 1234 
     driver-Class-Name: com.mysql.cj.jdbc.Driver

  session:
    jdbc:
      initialize-schema: always
    
  jpa:    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    show-sql: true
    hibernate:
       format_sql: true
       ddl-auto: create


server: port: 8080
 tomcat:
    file-encoding: UTF-8
    
 servlet:    encoding:      charset: UTF-8
      enabled: true
      force: true
            
    jsp:
      init-parameters:
        development: true
    session:
      timeout: 7200
 error:   whitelabel:     enabled: false
mybatis:
 type-aliases-package: com.project.example.domain
 mapper-locations: mapper/**/*.xml

logging:  config: classpath:logback-spring.xml
  
            